name: Deploy to Glitch
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'     
        required: true
jobs:
 repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "GalenBry/buffet"
        SOURCE_BRANCH: "refs/tags/${{ github.event.inputs.tag }}"
        DESTINATION_REPO: ${{ secrets.glitch_git_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
