name: Deploy to Glitch
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'     
        required: true
jobs:
  sync_git_repo:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "deploy triggered for tag: ${{ github.event.inputs.tag }}"
